In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('country.csv')
data

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,"419,9","0,00","2,98","19,62",800.0,NaN,"145,2","16,9","18,97","64,13",3,"31,67","3,92","0,09","0,28","0,63"
223,Western Sahara,NORTHERN AFRICA,273008,266000,"1,0","0,42",NaN,NaN,NaN,NaN,NaN,"0,02",0,"99,98",1,NaN,NaN,NaN,NaN,"0,4"
224,Yemen,NEAR EAST,21456188,527970,"40,6","0,36",0,"61,5",800.0,"50,2","37,2","2,78","0,24","96,98",1,"42,89","8,3","0,135","0,472","0,393"
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,"15,3","0,00",0,"88,29",800.0,"80,6","8,2","7,08","0,03","92,9",2,41,"19,93","0,22","0,29","0,489"
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,"31,3","0,00",0,"67,69",1900.0,"90,7","26,8","8,32","0,34","91,34",2,"28,01","21,84","0,179","0,243","0,579"

##  Country.csv dosyasının özelliği
Bu tablo, çeşitli ülkelerle ilgili bir dizi demografik, ekonomik ve coğrafi veriyi içermektedir. Tabloda her bir satır bir ülkeyi temsil ederken, sütunlar bu ülkelerle ilgili farklı özellikleri gösterir. İşte sütunların anlamları:

Country: Ülkenin adı.  
Region: Ülkenin bulunduğu bölge (örneğin, Asya, Doğu Avrupa).  
Population: Ülkenin toplam nüfusu.  
Area (sq. mi.): Ülkenin yüzölçümü (mil kare olarak).  
Pop. Density (per sq. mi.): Nüfus yoğunluğu (mil kare başına düşen kişi sayısı).  
Coastline (coast/area ratio): Sahil uzunluğunun, ülkenin toplam alanına oranı.  
Net migration: Net göç oranı (göçmenlerin ülkeye giren veya ülkeden çıkan kişi sayısına göre oranı).  
Infant mortality (per 1000 births): Bebek ölüm oranı (1000 doğum başına).  
GDP ($ per capita): Kişi başına düşen Gayri Safi Yurtiçi Hasıla (GSYİH).  
Literacy (%): Okur-yazarlık oranı.  
Phones (per 1000): Her 1000 kişi başına düşen telefon sayısı.  
Arable (%): Tarıma elverişli arazi yüzdesi.  
Crops (%): Ekilebilir ürünlerin yüzdesi.  
Other (%): Diğer arazi kullanımı yüzdesi.  
Climate: Ülkenin iklim kategorisi (numerik bir değer olarak gösterilmiş).  
Birthrate: Doğum oranı.  
Deathrate: Ölüm oranı.  
Agriculture: Tarım sektörünün ekonomideki payı.  
Industry: Sanayi sektörünün ekonomideki payı.  
Service: Hizmet sektörünün ekonomideki payı.

## Bu Dosyada Yapacağınız görevleri alt taraftan bakabilirsiniz.

## 1. Görev : Nüfusa Göre Azalan Sırada Sıralama:

In [ ]:
# Nüfusa Göre Azalan Sırada Sıralama kodunu buraya yazınız

sorted_data = data.sort_values(by='Population', ascending=False)
print(sorted_data)

                   Country                               Region  Population  \
42                  China         ASIA (EX. NEAR EAST)           1313973713
94                  India         ASIA (EX. NEAR EAST)           1095351995
214         United States   NORTHERN AMERICA                      298444215
95              Indonesia         ASIA (EX. NEAR EAST)            245452739
27                 Brazil               LATIN AMER. & CARIB       188078227
..                     ...                                  ...         ...
144                 Nauru   OCEANIA                                   13287
209                Tuvalu   OCEANIA                                   11810
140            Montserrat               LATIN AMER. & CARIB            9439
171          Saint Helena   SUB-SAHARAN AFRICA                         7502
174  St Pierre & Miquelon   NORTHERN AMERICA                           7026

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
42          9596960                      136,9                         0,15
94          3287590                      333,2                         0,21
214         9631420                       31,0                         0,21
95          1919440                      127,9                         2,85
27          8511965                       22,1                         0,09
..              ...                        ...                          ...
144              21                      632,7                       142,86
209              26                      454,2                        92,31
140             102                       92,5                        39,22
171             413                       18,2                        14,53
174             242                       29,0                        49,59

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
42           -0,4                              24,18              5000.0
94          -0,07                              56,29              2900.0
214          3,41                                6,5             37800.0
95              0                               35,6              3200.0
27          -0,03                              29,61              7600.0
..            ...                                ...                 ...
144             0                               9,95              5000.0
209             0                              20,03              1100.0
140             0                               7,35              3400.0
171             0                                 19              2500.0
174         -4,86                               7,54              6900.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
42          90,9             266,7       15,4      1,25     83,35     1,5
94          59,5              45,4       54,4      2,74     42,86     2,5
214         97,0             898,0      19,13      0,22     80,65       3
95          87,9              52,0      11,32      7,23     81,45       2
27          86,4             225,3       6,96       0,9     92,15       2
..           ...               ...        ...       ...       ...     ...
144          NaN             143,0          0         0       100       2
209          NaN              59,3          0         0       100       2
140         97,0               NaN         20         0        80       2
171         97,0             293,3       12,9         0      87,1     NaN
174         99,0             683,2      13,04         0     86,96     NaN

    Birthrate Deathrate Agriculture Industry Service
42      13,25      6,97       0,125    0,473   0,403
94      22,01      8,18       0,186    0,276   0,538
214     14,14      8,26        0,01    0,204   0,787
95      20,34      6,25       0,134    0,458   0,408
27      16,56      6,17       0,084      0,4   0,516
..        ...       ...         ...      ...     ...
144     24,76       6,7         NaN      NaN     NaN
209     22,18      7,11       0,166    0,272   0,562
140     17,59       7,1         NaN      NaN     NaN
171     12,13      6,53         NaN      NaN     NaN
174     13,52      6,83         NaN      NaN     NaN

[227 rows x 20 columns]

## 2. Görev: GDP per capita sütununa göre ülkeleri artan sırada sıralamak(Kişi başına düşen Gayri Safi Yurtiçi Hasıla).

In [ ]:
# GDP per capita sütununa göre ülkeleri artan sırada sıralamak(Kişi başına düşen Gayri Safi Yurtiçi Hasıla). kodunu buradan yazınız.

sorted_data = data.sort_values(by='GDP ($ per capita)', ascending=True)
print(sorted_data)

             Country                               Region  Population  \
58       East Timor         ASIA (EX. NEAR EAST)              1062777
188         Somalia   SUB-SAHARAN AFRICA                      8863338
183    Sierra Leone   SUB-SAHARAN AFRICA                      6005250
33          Burundi   SUB-SAHARAN AFRICA                      8090068
200        Tanzania   SUB-SAHARAN AFRICA                     37445392
..               ...                                  ...         ...
22          Bermuda   NORTHERN AMERICA                          65773
214   United States   NORTHERN AMERICA                      298444215
154          Norway   WESTERN EUROPE                          4610820
121      Luxembourg   WESTERN EUROPE                           474413
223  Western Sahara   NORTHERN AFRICA                          273008

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
58            15007                       70,8                         4,70
188          637657                       13,9                         0,47
183           71740                       83,7                         0,56
33            27830                      290,7                         0,00
200          945087                       39,6                         0,15
..              ...                        ...                          ...
22               53                     1241,0                       194,34
214         9631420                       31,0                         0,21
154          323802                       14,2                         7,77
121            2586                      183,5                         0,00
223          266000                        1,0                         0,42

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
58              0                              47,41               500.0
188          5,37                              116,7               500.0
183             0                             143,64               500.0
33          -0,06                              69,29               600.0
200         -2,06                              98,54               600.0
..            ...                                ...                 ...
22           2,49                               8,53             36000.0
214          3,41                                6,5             37800.0
154          1,74                                3,7             37800.0
121          8,97                               4,81             55100.0
223           NaN                                NaN                 NaN

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
58          58,6               NaN       4,71      0,67     94,62       2
188         37,8              11,3       1,67      0,04     98,29       1
183         31,4               4,0       6,98      0,89     92,13       2
33          51,6               3,4      35,05     14,02     50,93       2
200         78,2               4,0       4,52      1,08      94,4     NaN
..           ...               ...        ...       ...       ...     ...
22          98,0             851,4         20         0        80       2
214         97,0             898,0      19,13      0,22     80,65       3
154        100,0             461,7       2,87         0     97,13       3
121        100,0             515,4      23,28       0,4     76,32     NaN
223          NaN               NaN       0,02         0     99,98       1

    Birthrate Deathrate Agriculture Industry Service
58      26,99      6,24       0,085    0,231   0,684
188     45,13     16,63        0,65      0,1    0,25
183     45,76     23,03        0,49     0,31    0,21
33      42,22     13,46       0,463    0,203   0,334
200     37,71     16,39       0,432    0,172   0,396
..        ...       ...         ...      ...     ...
22       11,4      7,74        0,01      0,1    0,89
214     14,14      8,26        0,01    0,204   0,787
154     11,46       9,4       0,021    0,415   0,564
121     11,94      8,41        0,01     0,13    0,86
223       NaN       NaN         NaN      NaN     0,4

[227 rows x 20 columns]

## 3. Görev: Population sütunu 10 milyonun üzerinde olan ülkeleri seçmek.

In [ ]:
# Kodunu buraya yazınız.

filtered_data = data[data['Population'] > 10000000]
print(filtered_data)

          Country                               Region  Population  \
0    Afghanistan         ASIA (EX. NEAR EAST)             31056997
2        Algeria   NORTHERN AFRICA                        32930091
5         Angola   SUB-SAHARAN AFRICA                     12127071
8      Argentina               LATIN AMER. & CARIB        39921833
11     Australia   OCEANIA                                20264082
..            ...                                  ...         ...
218    Venezuela               LATIN AMER. & CARIB        25730435
219      Vietnam         ASIA (EX. NEAR EAST)             84402966
224        Yemen   NEAR EAST                              21456188
225       Zambia   SUB-SAHARAN AFRICA                     11502010
226     Zimbabwe   SUB-SAHARAN AFRICA                     12236805

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0            647500                       48,0                         0,00
2           2381740                       13,8                         0,04
5           1246700                        9,7                         0,13
8           2766890                       14,4                         0,18
11          7686850                        2,6                         0,34
..              ...                        ...                          ...
218          912050                       28,2                         0,31
219          329560                      256,1                         1,05
224          527970                       40,6                         0,36
225          752614                       15,3                         0,00
226          390580                       31,3                         0,00

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0           23,06                             163,07               700.0
2           -0,39                                 31              6000.0
5               0                             191,19              1900.0
8            0,61                              15,18             11200.0
11           3,98                               4,69             29000.0
..            ...                                ...                 ...
218         -0,04                               22,2              4800.0
219         -0,45                              25,95              2500.0
224             0                               61,5               800.0
225             0                              88,29               800.0
226             0                              67,69              1900.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0           36,0               3,2      12,13      0,22     87,65       1
2           70,0              78,1       3,22      0,25     96,53       1
5           42,0               7,8       2,41      0,24     97,35     NaN
8           97,1             220,4      12,31      0,48     87,21       3
11         100,0             565,5       6,55      0,04     93,41       1
..           ...               ...        ...       ...       ...     ...
218         93,4             140,1       2,95      0,92     96,13       2
219         90,3             187,7      19,97      5,95     74,08       2
224         50,2              37,2       2,78      0,24     96,98       1
225         80,6               8,2       7,08      0,03      92,9       2
226         90,7              26,8       8,32      0,34     91,34       2

    Birthrate Deathrate Agriculture Industry Service
0        46,6     20,34        0,38     0,24    0,38
2       17,14      4,61       0,101      0,6   0,298
5       45,11      24,2       0,096    0,658   0,246
8       16,73      7,55       0,095    0,358   0,547
11      12,14      7,51       0,038    0,262     0,7
..        ...       ...         ...      ...     ...
218     18,71      4,92        0,04    0,419   0,541
219     16,86      6,22       0,209     0,41   0,381
224     42,89       8,3       0,135    0,472   0,393
225        41     19,93        0,22     0,29   0,489
226     28,01     21,84       0,179    0,243   0,579

[79 rows x 20 columns]

## 4. Görev: Literacy (%) sütununa göre ülkeleri sıralayıp, en yüksek okur-yazarlık oranına sahip ilk 5 ülkeyi seçmek.

In [ ]:
# Kodunu buraya yazınız.

sorted_data = data.sort_values(by='Literacy (%)', ascending=False)
top_5_literacy = sorted_data.head(5)
print(top_5_literacy)

             Country                               Region  Population  \
53   Czech Republic   EASTERN EUROPE                         10235455
93          Iceland   WESTERN EUROPE                           299388
163          Poland   EASTERN EUROPE                         38536869
114          Latvia   BALTICS                                 2274735
64          Estonia   BALTICS                                 1324333

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
53            78866                      129,8                         0,00
93           103000                        2,9                         4,83
163          312685                      123,3                         0,16
114           64589                       35,2                         0,82
64            45226                       29,3                         8,39

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
53           0,97                               3,93             15700.0
93           2,38                               3,31             30900.0
163         -0,49                               8,51             11100.0
114         -2,23                               9,55             10200.0
64          -3,16                               7,87             12300.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
53          99,9             314,3       39,8      3,05     57,15       3
93          99,9             647,7       0,07         0     99,93       3
163         99,8             306,3      45,91      1,12     52,97       3
114         99,8             321,4      29,67      0,47     69,86       3
64          99,8             333,8      16,04      0,45     83,51       3

    Birthrate Deathrate Agriculture Industry Service
53       9,02     10,59       0,034    0,393   0,573
93      13,64      6,72       0,086     0,15   0,765
163      9,85      9,89        0,05    0,311    0,64
114      9,24     13,66        0,04    0,261   0,699
64      10,04     13,25        0,04    0,294   0,666

## 5. Görev:  Kişi Başı GSYİH 10.000'in Üzerinde Olan Ülkeleri Filtreleme: GDP ( per capita) sütunu 10.000'in üzerinde olan ülkeleri seçmek.

In [ ]:
# Kodunu buraya yazınız.

filtered_data = data[data['GDP ($ per capita)'] > 10000]
print(filtered_data)

                   Country                               Region  Population  \
4                 Andorra   WESTERN EUROPE                            71201
7       Antigua & Barbuda               LATIN AMER. & CARIB           69108
8               Argentina               LATIN AMER. & CARIB        39921833
10                  Aruba               LATIN AMER. & CARIB           71891
11              Australia   OCEANIA                                20264082
..                     ...                                  ...         ...
212  United Arab Emirates   NEAR EAST                               2602713
213        United Kingdom   WESTERN EUROPE                         60609153
214         United States   NORTHERN AMERICA                      298444215
215               Uruguay               LATIN AMER. & CARIB         3431932
220        Virgin Islands               LATIN AMER. & CARIB          108605

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
4               468                      152,1                         0,00
7               443                      156,0                        34,54
8           2766890                       14,4                         0,18
10              193                      372,5                        35,49
11          7686850                        2,6                         0,34
..              ...                        ...                          ...
212           82880                       31,4                         1,59
213          244820                      247,6                         5,08
214         9631420                       31,0                         0,21
215          176220                       19,5                         0,37
220            1910                       56,9                         9,84

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
4             6,6                               4,05             19000.0
7           -6,15                              19,46             11000.0
8            0,61                              15,18             11200.0
10              0                               5,89             28000.0
11           3,98                               4,69             29000.0
..            ...                                ...                 ...
212          1,03                              14,51             23200.0
213          2,19                               5,16             27700.0
214          3,41                                6,5             37800.0
215         -0,32                              11,95             12800.0
220         -8,94                               8,03             17200.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
4          100,0             497,2       2,22         0     97,78       3
7           89,0             549,9      18,18      4,55     77,27       2
8           97,1             220,4      12,31      0,48     87,21       3
10          97,0             516,1      10,53         0     89,47       2
11         100,0             565,5       6,55      0,04     93,41       1
..           ...               ...        ...       ...       ...     ...
212         77,9             475,3        0,6      2,25     97,15       1
213         99,0             543,5      23,46      0,21     76,33       3
214         97,0             898,0      19,13      0,22     80,65       3
215         98,0             291,4       7,43      0,23     92,34       3
220          NaN             652,8      11,76      2,94      85,3       2

    Birthrate Deathrate Agriculture Industry Service
4        8,71      6,25         NaN      NaN     NaN
7       16,93      5,37       0,038     0,22   0,743
8       16,73      7,55       0,095    0,358   0,547
10      11,03      6,68       0,004    0,333   0,663
11      12,14      7,51       0,038    0,262     0,7
..        ...       ...         ...      ...     ...
212     18,96       4,4        0,04    0,585   0,375
213     10,71     10,13       0,005    0,237   0,758
214     14,14      8,26        0,01    0,204   0,787
215     13,91      9,05       0,093    0,311   0,596
220     13,96      6,43        0,01     0,19     0,8

[76 rows x 20 columns]

## Görev 6 : En Yüksek Nüfus Yoğunluğuna Sahip İlk 10 Ülkeyi Seçme:
Pop. Density (per sq. mi.) sütununa göre ülkeleri sıralayıp, en yüksek nüfus yoğunluğuna sahip ilk 10 ülkeyi seçmek.

In [ ]:
sorted_data = data.sort_values(by='Pop. Density (per sq. mi.)', ascending=False)
top_10_population_density = sorted_data.head(10)
print(top_10_population_density)

         Country                               Region  Population  \
9       Armenia                  C.W. OF IND. STATES      2976372
186    Slovenia   EASTERN EUROPE                          2010347
202        Togo   SUB-SAHARAN AFRICA                      5548702
12      Austria   WESTERN EUROPE                          8192880
168     Romania   EASTERN EUROPE                         22303552
77        Ghana   SUB-SAHARAN AFRICA                     22409572
140  Montserrat               LATIN AMER. & CARIB            9439
13   Azerbaijan                  C.W. OF IND. STATES      7961619
56     Dominica               LATIN AMER. & CARIB           68910
206      Turkey   NEAR EAST                              70413958

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
9             29800                       99,9                         0,00
186           20273                       99,2                         0,23
202           56785                       97,7                         0,10
12            83870                       97,7                         0,00
168          237500                       93,9                         0,09
77           239460                       93,6                         0,23
140             102                       92,5                        39,22
13            86600                       91,9                         0,00
56              754                       91,4                        19,63
206          780580                       90,2                         0,92

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
9           -6,47                              23,28              3500.0
186          1,12                               4,45             19000.0
202             0                              66,61              1500.0
12              2                               4,66             30000.0
168         -0,13                              26,43              7000.0
77          -0,64                              51,43              2200.0
140             0                               7,35              3400.0
13           -4,9                              81,74              3400.0
56         -13,87                              14,15              5400.0
206             0                              41,04              6700.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
9           98,6             195,7      17,55       2,3     80,15       4
186         99,7             406,1        8,6      1,49     89,91     NaN
202         60,9              10,6      46,15      2,21     51,64       2
12          98,0             452,2      16,91      0,86     82,23       3
168         98,4             196,9      40,82      2,25     56,93       3
77          74,8              14,4      16,26      9,67     74,07       2
140         97,0               NaN         20         0        80       2
13          97,0             137,1      19,63      2,71     77,66       1
56          94,0             304,8       6,67        20     73,33       2
206         86,5             269,5      30,93      3,31     65,76       3

    Birthrate Deathrate Agriculture Industry Service
9       12,07      8,23       0,239    0,343   0,418
186      8,98     10,31       0,028    0,369   0,603
202     37,01      9,83       0,395    0,204   0,401
12       8,74      9,76       0,018    0,304   0,678
168      10,7     11,77       0,101     0,35   0,549
77      30,52      9,72       0,366    0,246   0,387
140     17,59       7,1         NaN      NaN     NaN
13      20,74      9,75       0,141    0,457   0,402
56      15,27      6,73       0,177    0,328   0,495
206     16,62      5,97       0,117    0,298   0,585